name: robstettler
favicon: null
layout_spectrum: 0.26549
typography_spectrum: 0.36843075952492654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02040f'
    - '#103a79'
    - '#1a72c1'
    - '#d9d9d9'
    - '#498abb'
  brandStrength: 0.8168458873406053
  lightness: 0.6092954622581601
  saturation: 0.6052762849722058
  rhythmicContrast: 0.19267426966689527
purpose: []
